services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pianito
      POSTGRES_PASSWORD: pianito
      POSTGRES_DB: pianito
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
