export default {
  common: {
    pianito: "pianito",
    signIn: "Sign in",
    signUp: "Sign up",
    signOut: "Sign out",
    settings: "Settings",
    retry: "Retry",
    previous: "Previous",
    next: "Next",
    start: "Start",
    loading: "Loading...",
    cancel: "Cancel",
  },
  home: {
    tagline: "Learn piano, read music, master chords.",
    readMusic: "Read Music",
    readMusicDescription:
      "Learn to read music notation with interactive exercises.",
    chords: "Chords",
    chordsDescription: "Visualize and learn chords with scale degrees.",
    playSongs: "Play Songs",
    playSongsDescription: "Play along with backing tracks and accompaniment.",
    accompaniment: "Accompaniment",
    accompanimentDescription: "Create chord charts and play them back.",
  },
  auth: {
    createAccount: "Create account",
    startJourney: "Start your piano journey.",
    welcomeBack: "Welcome back to pianito.",
    name: "Name",
    namePlaceholder: "Your name",
    email: "Email",
    emailPlaceholder: "you@example.com",
    password: "Password",
    passwordPlaceholder: "••••••••",
    creatingAccount: "Creating account...",
    signingIn: "Signing in...",
    failedCreate: "Failed to create account",
    failedSignIn: "Failed to sign in",
    alreadyHaveAccount: "Already have an account? ",
    dontHaveAccount: "Don't have an account? ",
  },
  read: {
    title: "Read Music",
    description: "Learn to read notes on the staff, one step at a time.",
    levels: "Levels",
    level: "Level {{level}}",
    levelProgress: "Level {{current}}/{{total}}",
    score: "Score: {{score}}/{{total}}",
    nextLevel: "Next Level",
    correct: "Correct!",
    wrong: "Wrong!",
    loadingExercise: "Loading exercise...",
    instructions:
      "Press any note button to begin. Identify each note as it reaches the orange zone. You can also use your keyboard (C, D, E, F, G, A, B).",
    notesAndTempo: "{{notes}} notes · {{tempo}} bpm",
  },
  intro: {
    thisIsA: "This is a ",
    dontShowAgain: "Don't show again for this level",
    pageProgress: "{{current}} / {{total}}",
  },
  results: {
    exerciseComplete: "Exercise Complete!",
    scoreDisplay: "{{score}}/{{total}}",
    perfectScore: "Perfect score!",
    greatJob: "Great job!",
    keepPracticing: "Keep practicing!",
  },
  accomp: {
    title: "Accompaniment",
    description: "Create chord charts and play them back.",
    createNew: "Create New Grid",
    untitled: "Untitled",
    gridName: "Grid name",
    timeSignature: "Time sig.",
    tempo: "Tempo",
    bpm: "BPM",
    loopCount: "Loops",
    metronome: "Metronome",
    chords: "Chords",
    bass: "Bass",
    drums: "Drums",
    swing: "Swing",
    style: "Style",
    styleOff: "Off",
    styles: {
      rock: "Rock",
      pop: "Pop",
      bossaNova: "Bossa Nova",
      jazz: "Jazz",
      funk: "Funk",
      reggae: "Reggae",
    },
    play: "Play",
    stop: "Stop",
    save: "Save",
    saved: "Saved",
    saving: "Saving...",
    addSquare: "Add square",
    addLine: "Add line",
    removeLine: "Remove line",
    clearChord: "Clear",
    searchChord: "Search chord...",
    emptySquare: "Empty",
    noGrids: "No grids yet. Create your first one!",
    deleteGrid: "Delete",
    deleteGridConfirm: "Are you sure you want to delete this grid?",
    createdAt: "Created {{date}}",
    loadError: "Failed to load grid.",
    noResults: "No matching chords.",
    dragToReorder: "Drag to reorder",
    repeatCount: "Repeat",
    mergeGroup: "Merge groups",
    deleteGroup: "Delete group",
    splitHere: "Split here",
    splitGroup: "Split group at this line",
    selectedCount: "{{count}} selected",
    groupSelection: "Group",
    clearChords: "Clear chords",
    deleteSelection: "Delete",
    loopSelection: "Loop",
    authRequired: "Account Required",
    authRequiredDescription:
      "Create an account to save and manage your chord grids.",
    composer: "Composer",
    composerPlaceholder: "e.g. Miles Davis",
    key: "Key",
    keyPlaceholder: "e.g. Cm",
    visibility: "Visibility",
    private: "Private",
    public: "Public",
    community: "Community",
    searchPublicGrids: "Search by name, composer, or key...",
    publicGrids: "Public Grids",
    publicGridsDescription: "Browse and play grids shared by other users.",
    noPublicGrids: "No public grids yet.",
    transpose: "Transpose",
    semitones: "semitones",
    readOnly: "Read-only",
  },
  tour: {
    helpButton: "Tour",
    back: "Back",
    next: "Next",
    done: "Done",
    gridName: {
      title: "Grid Name",
      text: "Click the name to rename your chord progression.",
    },
    gridOverview: {
      title: "The Grid",
      text: "This is your chord grid. Each square represents a chord in your progression. Drag squares to reorder them.",
    },
    gridSquare: {
      title: "Chord Squares",
      text: "Click any square to open the chord search and assign a chord.",
    },
    chordSearch: {
      title: "Chord Search",
      text: "Type to search through chords. Press Enter to select the first match, or click any chord in the list.",
    },
    resizeHandle: {
      title: "Beat Count",
      text: "Drag the right edge of a square to change its beat count between 2 and 4 beats.",
    },
    addSquare: {
      title: "Add Squares",
      text: "Click the + button to add a new square to your grid.",
    },
    multiSelect: {
      title: "Multi-Select",
      text: "Hold Ctrl (or Cmd on Mac) and click to select multiple squares. Use Shift+Click to select a range.",
    },
    selectionToolbar: {
      title: "Selection Actions",
      text: "When squares are selected, use this toolbar to group them, clear their chords, or delete them.",
    },
    playButton: {
      title: "Playback",
      text: "Press Play to hear your chord progression. Press Stop to pause.",
    },
    tempo: {
      title: "Tempo",
      text: "Set the playback speed in beats per minute (30-300 BPM).",
    },
    loops: {
      title: "Loops",
      text: "Set how many times the grid repeats during playback.",
    },
    instruments: {
      title: "Instruments",
      text: "Toggle which instruments play: metronome, chords, bass, and drums.",
    },
    styleSelect: {
      title: "Musical Style",
      text: "Choose a musical style like Rock, Jazz, or Bossa Nova to change the accompaniment pattern.",
    },
    swing: {
      title: "Swing",
      text: "Adjust the swing feel from straight (0%) to full swing (100%).",
    },
    saveButton: {
      title: "Save",
      text: "Save your grid. The button is enabled when you have unsaved changes.",
    },
  },
  settings: {
    title: "Settings",
    language: "Language",
    languageDescription: "Choose the language for the app interface.",
    notation: "Notation",
    notationDescription:
      "Choose how notes are displayed: letter names (A, B, C) or solfege (Do, Ré, Mi).",
    theme: "Theme",
    themeDescription: "Choose the color theme for the app.",
    dangerZone: "Danger Zone",
    deleteAccount: "Delete Account",
    deleteAccountDescription:
      "Permanently delete your account and all associated data. This action cannot be undone.",
    deleteAccountConfirmation:
      "This will permanently delete your account, progress, and all data. This action cannot be undone.",
    typeDelete: 'Type "DELETE" to confirm:',
    deleteButton: "Delete My Account",
    deleting: "Deleting...",
  },
} as const;
