export default {
  common: {
    pianito: "pianito",
    signIn: "Sign in",
    signUp: "Sign up",
    signOut: "Sign out",
    settings: "Settings",
    retry: "Retry",
    previous: "Previous",
    next: "Next",
    start: "Start",
    loading: "Loading...",
    cancel: "Cancel",
  },
  home: {
    tagline: "Learn piano, read music, master chords.",
    readMusic: "Read Music",
    readMusicDescription:
      "Learn to read music notation with interactive exercises.",
    chords: "Chords",
    chordsDescription: "Visualize and learn chords with scale degrees.",
    playSongs: "Play Songs",
    playSongsDescription: "Play along with backing tracks and accompaniment.",
  },
  auth: {
    createAccount: "Create account",
    startJourney: "Start your piano journey.",
    welcomeBack: "Welcome back to pianito.",
    name: "Name",
    namePlaceholder: "Your name",
    email: "Email",
    emailPlaceholder: "you@example.com",
    password: "Password",
    passwordPlaceholder: "••••••••",
    creatingAccount: "Creating account...",
    signingIn: "Signing in...",
    failedCreate: "Failed to create account",
    failedSignIn: "Failed to sign in",
    alreadyHaveAccount: "Already have an account? ",
    dontHaveAccount: "Don't have an account? ",
  },
  read: {
    title: "Read Music",
    description:
      "Progress through scales, from natural notes to four accidentals.",
    trebleClef: "Treble Clef",
    bassClef: "Bass Clef",
    levels: "Levels",
    level: "Level {{level}}",
    levelProgress: "Level {{current}}/{{total}}",
    score: "Score: {{score}}/{{total}}",
    nextLevel: "Next Level",
    correct: "Correct!",
    wrong: "Wrong!",
    loadingExercise: "Loading exercise...",
    instructions:
      "Press any note button to begin. Identify each note as it reaches the orange zone. You can also use your keyboard (C, D, E, F, G, A, B) or connect a MIDI piano.",
    notesAndTempo: "{{degrees}} notes · {{tempo}} bpm",
  },
  intro: {
    thisIsA: "This is a ",
    dontShowAgain: "Don't show again for this level",
    pageProgress: "{{current}} / {{total}}",
  },
  results: {
    exerciseComplete: "Exercise Complete!",
    scoreDisplay: "{{score}}/{{total}}",
    perfectScore: "Perfect score!",
    greatJob: "Great job!",
    keepPracticing: "Keep practicing!",
  },
  settings: {
    title: "Settings",
    language: "Language",
    languageDescription: "Choose the language for the app interface.",
    notation: "Notation",
    notationDescription:
      "Choose how notes are displayed: letter names (A, B, C) or solfege (Do, Ré, Mi).",
    theme: "Theme",
    themeDescription: "Choose the color theme for the app.",
    dangerZone: "Danger Zone",
    deleteAccount: "Delete Account",
    deleteAccountDescription:
      "Permanently delete your account and all associated data. This action cannot be undone.",
    deleteAccountConfirmation:
      "This will permanently delete your account, progress, and all data. This action cannot be undone.",
    typeDelete: 'Type "DELETE" to confirm:',
    deleteButton: "Delete My Account",
    deleting: "Deleting...",
  },
  midi: {
    title: "MIDI",
    connected: "Connected",
    connecting: "Connecting",
    disconnected: "Disconnected",
    connect: "Connect",
    disconnect: "Disconnect",
    enable: "Enable MIDI",
    permissionDenied:
      "MIDI access was denied. Please enable it in your browser settings.",
  },
} as const;
