export default {
  common: {
    pianito: "pianito",
    signIn: "Sign in",
    signUp: "Sign up",
    signOut: "Sign out",
    settings: "Settings",
    retry: "Retry",
    previous: "Previous",
    next: "Next",
    start: "Start",
    loading: "Loading...",
    cancel: "Cancel",
  },
  home: {
    tagline: "Learn piano, read music, master chords.",
    readMusic: "Read Music",
    readMusicDescription:
      "Learn to read music notation with interactive exercises.",
    chords: "Chords",
    chordsDescription: "Visualize and learn chords with scale degrees.",
    playSongs: "Play Songs",
    playSongsDescription: "Play along with backing tracks and accompaniment.",
    accompaniment: "Accompaniment",
    accompanimentDescription: "Create chord charts and play them back.",
  },
  auth: {
    createAccount: "Create account",
    startJourney: "Start your piano journey.",
    welcomeBack: "Welcome back to pianito.",
    name: "Name",
    namePlaceholder: "Your name",
    email: "Email",
    emailPlaceholder: "you@example.com",
    password: "Password",
    passwordPlaceholder: "••••••••",
    creatingAccount: "Creating account...",
    signingIn: "Signing in...",
    failedCreate: "Failed to create account",
    failedSignIn: "Failed to sign in",
    alreadyHaveAccount: "Already have an account? ",
    dontHaveAccount: "Don't have an account? ",
  },
  read: {
    title: "Read Music",
    description:
      "Progress through scales, from natural notes to four accidentals.",
    trebleClef: "Treble Clef",
    bassClef: "Bass Clef",
    levels: "Levels",
    level: "Level {{level}}",
    levelProgress: "Level {{current}}/{{total}}",
    score: "Score: {{score}}/{{total}}",
    nextLevel: "Next Level",
    correct: "Correct!",
    wrong: "Wrong!",
    loadingExercise: "Loading exercise...",
    instructions:
      "Press any note button to begin. Identify each note as it reaches the orange zone. You can also use your keyboard (C, D, E, F, G, A, B).",
    notesAndTempo: "{{degrees}} notes · {{tempo}} bpm",
  },
  intro: {
    thisIsA: "This is a ",
    dontShowAgain: "Don't show again for this level",
    pageProgress: "{{current}} / {{total}}",
  },
  results: {
    exerciseComplete: "Exercise Complete!",
    scoreDisplay: "{{score}}/{{total}}",
    perfectScore: "Perfect score!",
    greatJob: "Great job!",
    keepPracticing: "Keep practicing!",
  },
  accomp: {
    title: "Accompaniment",
    description: "Create chord charts and play them back.",
    createNew: "Create New Grid",
    untitled: "Untitled",
    gridName: "Grid name",
    tempo: "Tempo",
    bpm: "BPM",
    loopCount: "Loops",
    metronome: "Metronome",
    swing: "Swing",
    style: "Style",
    styleOff: "Off",
    styles: {
      rock: "Rock",
      pop: "Pop",
      bossaNova: "Bossa Nova",
      jazz: "Jazz",
      funk: "Funk",
      reggae: "Reggae",
    },
    play: "Play",
    stop: "Stop",
    save: "Save",
    saved: "Saved",
    saving: "Saving...",
    addSquare: "Add square",
    addLine: "Add line",
    removeLine: "Remove line",
    clearChord: "Clear",
    searchChord: "Search chord...",
    emptySquare: "Empty",
    noGrids: "No grids yet. Create your first one!",
    deleteGrid: "Delete",
    deleteGridConfirm: "Are you sure you want to delete this grid?",
    createdAt: "Created {{date}}",
    loadError: "Failed to load grid.",
    noResults: "No matching chords.",
    dragToReorder: "Drag to reorder",
    repeatCount: "Repeat",
    mergeGroup: "Merge groups",
    splitHere: "Split here",
    splitGroup: "Split group at this line",
    selectedCount: "{{count}} selected",
    groupSelection: "Group",
    authRequired: "Account Required",
    authRequiredDescription:
      "Create an account to save and manage your chord grids.",
  },
  settings: {
    title: "Settings",
    language: "Language",
    languageDescription: "Choose the language for the app interface.",
    notation: "Notation",
    notationDescription:
      "Choose how notes are displayed: letter names (A, B, C) or solfege (Do, Ré, Mi).",
    theme: "Theme",
    themeDescription: "Choose the color theme for the app.",
    dangerZone: "Danger Zone",
    deleteAccount: "Delete Account",
    deleteAccountDescription:
      "Permanently delete your account and all associated data. This action cannot be undone.",
    deleteAccountConfirmation:
      "This will permanently delete your account, progress, and all data. This action cannot be undone.",
    typeDelete: 'Type "DELETE" to confirm:',
    deleteButton: "Delete My Account",
    deleting: "Deleting...",
  },
} as const;
