export default {
  common: {
    pianito: "pianito",
    signIn: "Iniciar sesión",
    signUp: "Registrarse",
    signOut: "Cerrar sesión",
    settings: "Ajustes",
    retry: "Reintentar",
    previous: "Anterior",
    next: "Siguiente",
    start: "Empezar",
    loading: "Cargando...",
    cancel: "Cancelar",
  },
  home: {
    tagline: "Aprende piano, lee música, domina los acordes.",
    readMusic: "Leer música",
    readMusicDescription:
      "Aprende a leer partituras con ejercicios interactivos.",
    chords: "Acordes",
    chordsDescription: "Visualiza y aprende acordes con grados de escala.",
    playSongs: "Tocar canciones",
    playSongsDescription: "Toca con pistas de acompañamiento.",
    accompaniment: "Acompañamiento",
    accompanimentDescription: "Crea tablas de acordes y reprodúcelas.",
  },
  auth: {
    createAccount: "Crear cuenta",
    startJourney: "Comienza tu aventura musical.",
    welcomeBack: "Bienvenido de nuevo a pianito.",
    name: "Nombre",
    namePlaceholder: "Tu nombre",
    email: "Correo electrónico",
    emailPlaceholder: "tu@ejemplo.com",
    password: "Contraseña",
    passwordPlaceholder: "••••••••",
    creatingAccount: "Creando cuenta...",
    signingIn: "Iniciando sesión...",
    failedCreate: "Error al crear la cuenta",
    failedSignIn: "Error al iniciar sesión",
    alreadyHaveAccount: "¿Ya tienes una cuenta? ",
    dontHaveAccount: "¿No tienes una cuenta? ",
  },
  read: {
    title: "Leer música",
    description:
      "Progresa a través de las escalas, desde notas naturales hasta cuatro alteraciones.",
    trebleClef: "Clave de Sol",
    bassClef: "Clave de Fa",
    levels: "Niveles",
    level: "Nivel {{level}}",
    levelProgress: "Nivel {{current}}/{{total}}",
    score: "Puntuación: {{score}}/{{total}}",
    nextLevel: "Siguiente nivel",
    correct: "¡Correcto!",
    wrong: "¡Incorrecto!",
    loadingExercise: "Cargando ejercicio...",
    instructions:
      "Pulsa cualquier botón de nota para empezar. Identifica cada nota cuando llegue a la zona naranja. También puedes usar tu teclado (C, D, E, F, G, A, B).",
    notesAndTempo: "{{degrees}} notas · {{tempo}} bpm",
  },
  intro: {
    thisIsA: "Esto es un ",
    dontShowAgain: "No mostrar de nuevo para este nivel",
    pageProgress: "{{current}} / {{total}}",
  },
  results: {
    exerciseComplete: "¡Ejercicio completado!",
    scoreDisplay: "{{score}}/{{total}}",
    perfectScore: "¡Puntuación perfecta!",
    greatJob: "¡Buen trabajo!",
    keepPracticing: "¡Sigue practicando!",
  },
  accomp: {
    title: "Acompañamiento",
    description: "Crea tablas de acordes y reprodúcelas.",
    createNew: "Nueva cuadrícula",
    untitled: "Sin título",
    gridName: "Nombre de la cuadrícula",
    tempo: "Tempo",
    bpm: "BPM",
    loopCount: "Bucles",
    metronome: "Metrónomo",
    drumsOff: "Batería: Off",
    drums: {
      rock: "Rock",
      pop: "Pop",
      bossaNova: "Bossa Nova",
      jazz: "Jazz",
      funk: "Funk",
      reggae: "Reggae",
    },
    play: "Reproducir",
    stop: "Detener",
    save: "Guardar",
    saved: "Guardado",
    saving: "Guardando...",
    addSquare: "Añadir casilla",
    addLine: "Añadir línea",
    removeLine: "Eliminar línea",
    clearChord: "Borrar",
    searchChord: "Buscar acorde...",
    emptySquare: "Vacío",
    noGrids: "Aún no hay cuadrículas. ¡Crea la primera!",
    deleteGrid: "Eliminar",
    deleteGridConfirm: "¿Estás seguro de que quieres eliminar esta cuadrícula?",
    createdAt: "Creada el {{date}}",
    loadError: "Error al cargar la cuadrícula.",
    noResults: "No se encontraron acordes.",
    dragToReorder: "Arrastrar para reordenar",
    repeatCount: "Repeticiones",
    mergeGroup: "Fusionar grupos",
    splitHere: "Separar aquí",
    splitGroup: "Separar el grupo en esta línea",
    selectedCount: "{{count}} seleccionado(s)",
    groupSelection: "Agrupar",
    authRequired: "Cuenta requerida",
    authRequiredDescription:
      "Crea una cuenta para guardar y gestionar tus tablas de acordes.",
  },
  settings: {
    title: "Ajustes",
    language: "Idioma",
    languageDescription: "Elige el idioma de la interfaz de la aplicación.",
    notation: "Notación",
    notationDescription:
      "Elige cómo se muestran las notas: letras (A, B, C) o solfeo (Do, Re, Mi).",
    theme: "Tema",
    themeDescription: "Elige el tema de color de la aplicación.",
    dangerZone: "Zona de peligro",
    deleteAccount: "Eliminar cuenta",
    deleteAccountDescription:
      "Elimina permanentemente tu cuenta y todos los datos asociados. Esta acción no se puede deshacer.",
    deleteAccountConfirmation:
      "Esto eliminará permanentemente tu cuenta, tu progreso y todos tus datos. Esta acción no se puede deshacer.",
    typeDelete: 'Escribe "DELETE" para confirmar:',
    deleteButton: "Eliminar mi cuenta",
    deleting: "Eliminando...",
  },
} as const;
