export default {
  common: {
    pianito: "pianito",
    signIn: "Se connecter",
    signUp: "S'inscrire",
    signOut: "Se déconnecter",
    settings: "Paramètres",
    retry: "Réessayer",
    previous: "Précédent",
    next: "Suivant",
    start: "Commencer",
    loading: "Chargement...",
    cancel: "Annuler",
  },
  home: {
    tagline: "Apprenez le piano, lisez la musique, maîtrisez les accords.",
    readMusic: "Lire la musique",
    readMusicDescription:
      "Apprenez à lire les partitions avec des exercices interactifs.",
    chords: "Accords",
    chordsDescription:
      "Visualisez et apprenez les accords avec les degrés de gamme.",
    playSongs: "Jouer des morceaux",
    playSongsDescription: "Jouez avec des pistes d'accompagnement.",
    accompaniment: "Accompagnement",
    accompanimentDescription: "Créez des grilles d'accords et jouez-les.",
  },
  auth: {
    createAccount: "Créer un compte",
    startJourney: "Commencez votre aventure musicale.",
    welcomeBack: "Content de vous revoir sur pianito.",
    name: "Nom",
    namePlaceholder: "Votre nom",
    email: "Email",
    emailPlaceholder: "vous@exemple.com",
    password: "Mot de passe",
    passwordPlaceholder: "••••••••",
    creatingAccount: "Création du compte...",
    signingIn: "Connexion...",
    failedCreate: "Échec de la création du compte",
    failedSignIn: "Échec de la connexion",
    alreadyHaveAccount: "Vous avez déjà un compte ? ",
    dontHaveAccount: "Vous n'avez pas de compte ? ",
  },
  read: {
    title: "Lire la musique",
    description:
      "Progressez à travers les gammes, des notes naturelles aux quatre altérations.",
    trebleClef: "Clé de Sol",
    bassClef: "Clé de Fa",
    levels: "Niveaux",
    level: "Niveau {{level}}",
    levelProgress: "Niveau {{current}}/{{total}}",
    score: "Score : {{score}}/{{total}}",
    nextLevel: "Niveau suivant",
    correct: "Correct !",
    wrong: "Faux !",
    loadingExercise: "Chargement de l'exercice...",
    instructions:
      "Appuyez sur un bouton de note pour commencer. Identifiez chaque note lorsqu'elle atteint la zone orange. Vous pouvez aussi utiliser votre clavier (C, D, E, F, G, A, B).",
    notesAndTempo: "{{degrees}} notes · {{tempo}} bpm",
  },
  intro: {
    thisIsA: "Ceci est un ",
    dontShowAgain: "Ne plus afficher pour ce niveau",
    pageProgress: "{{current}} / {{total}}",
  },
  results: {
    exerciseComplete: "Exercice terminé !",
    scoreDisplay: "{{score}}/{{total}}",
    perfectScore: "Score parfait !",
    greatJob: "Bien joué !",
    keepPracticing: "Continuez à pratiquer !",
  },
  accomp: {
    title: "Accompagnement",
    description: "Créez des grilles d'accords et jouez-les.",
    createNew: "Nouvelle grille",
    untitled: "Sans titre",
    gridName: "Nom de la grille",
    tempo: "Tempo",
    bpm: "BPM",
    loopCount: "Boucles",
    play: "Jouer",
    stop: "Arrêter",
    save: "Enregistrer",
    saved: "Enregistré",
    saving: "Enregistrement...",
    addLine: "Ajouter une ligne",
    removeLine: "Supprimer la ligne",
    clearChord: "Effacer",
    searchChord: "Rechercher un accord...",
    emptySquare: "Vide",
    noGrids: "Aucune grille. Créez votre première !",
    deleteGrid: "Supprimer",
    deleteGridConfirm: "Voulez-vous vraiment supprimer cette grille ?",
    createdAt: "Créée le {{date}}",
    loadError: "Impossible de charger la grille.",
    noResults: "Aucun accord trouvé.",
    dragToReorder: "Glisser pour réordonner",
    authRequired: "Compte requis",
    authRequiredDescription:
      "Créez un compte pour sauvegarder et gérer vos grilles d'accords.",
  },
  settings: {
    title: "Paramètres",
    language: "Langue",
    languageDescription: "Choisissez la langue de l'interface.",
    notation: "Notation",
    notationDescription:
      "Choisissez l'affichage des notes : lettres (A, B, C) ou solfège (Do, Ré, Mi).",
    theme: "Thème",
    themeDescription: "Choisissez le thème de couleur de l'application.",
    dangerZone: "Zone de danger",
    deleteAccount: "Supprimer le compte",
    deleteAccountDescription:
      "Supprimez définitivement votre compte et toutes les données associées. Cette action est irréversible.",
    deleteAccountConfirmation:
      "Cela supprimera définitivement votre compte, votre progression et toutes vos données. Cette action est irréversible.",
    typeDelete: 'Tapez "DELETE" pour confirmer :',
    deleteButton: "Supprimer mon compte",
    deleting: "Suppression...",
  },
} as const;
