export default {
  common: {
    pianito: "pianito",
    signIn: "Se connecter",
    signUp: "S'inscrire",
    signOut: "Se déconnecter",
    settings: "Paramètres",
    retry: "Réessayer",
    previous: "Précédent",
    next: "Suivant",
    start: "Commencer",
    loading: "Chargement...",
    cancel: "Annuler",
  },
  home: {
    tagline: "Apprenez le piano, lisez la musique, maîtrisez les accords.",
    readMusic: "Lire la musique",
    readMusicDescription:
      "Apprenez à lire les partitions avec des exercices interactifs.",
    chords: "Accords",
    chordsDescription:
      "Visualisez et apprenez les accords avec les degrés de gamme.",
    playSongs: "Jouer des morceaux",
    playSongsDescription: "Jouez avec des pistes d'accompagnement.",
    accompaniment: "Accompagnement",
    accompanimentDescription: "Créez des grilles d'accords et jouez-les.",
  },
  auth: {
    createAccount: "Créer un compte",
    startJourney: "Commencez votre aventure musicale.",
    welcomeBack: "Content de vous revoir sur pianito.",
    name: "Nom",
    namePlaceholder: "Votre nom",
    email: "Email",
    emailPlaceholder: "vous@exemple.com",
    password: "Mot de passe",
    passwordPlaceholder: "••••••••",
    creatingAccount: "Création du compte...",
    signingIn: "Connexion...",
    failedCreate: "Échec de la création du compte",
    failedSignIn: "Échec de la connexion",
    alreadyHaveAccount: "Vous avez déjà un compte ? ",
    dontHaveAccount: "Vous n'avez pas de compte ? ",
  },
  read: {
    title: "Lire la musique",
    description:
      "Progressez à travers les gammes, des notes naturelles aux quatre altérations.",
    trebleClef: "Clé de Sol",
    bassClef: "Clé de Fa",
    levels: "Niveaux",
    level: "Niveau {{level}}",
    levelProgress: "Niveau {{current}}/{{total}}",
    score: "Score : {{score}}/{{total}}",
    nextLevel: "Niveau suivant",
    correct: "Correct !",
    wrong: "Faux !",
    loadingExercise: "Chargement de l'exercice...",
    instructions:
      "Appuyez sur un bouton de note pour commencer. Identifiez chaque note lorsqu'elle atteint la zone orange. Vous pouvez aussi utiliser votre clavier (C, D, E, F, G, A, B).",
    notesAndTempo: "{{degrees}} notes · {{tempo}} bpm",
  },
  intro: {
    thisIsA: "Ceci est un ",
    dontShowAgain: "Ne plus afficher pour ce niveau",
    pageProgress: "{{current}} / {{total}}",
  },
  results: {
    exerciseComplete: "Exercice terminé !",
    scoreDisplay: "{{score}}/{{total}}",
    perfectScore: "Score parfait !",
    greatJob: "Bien joué !",
    keepPracticing: "Continuez à pratiquer !",
  },
  accomp: {
    title: "Accompagnement",
    description: "Créez des grilles d'accords et jouez-les.",
    createNew: "Nouvelle grille",
    untitled: "Sans titre",
    gridName: "Nom de la grille",
    timeSignature: "Mesure",
    tempo: "Tempo",
    bpm: "BPM",
    loopCount: "Boucles",
    metronome: "Métronome",
    chords: "Accords",
    bass: "Basse",
    drums: "Batterie",
    swing: "Swing",
    style: "Style",
    styleOff: "Off",
    styles: {
      rock: "Rock",
      pop: "Pop",
      bossaNova: "Bossa Nova",
      jazz: "Jazz",
      funk: "Funk",
      reggae: "Reggae",
    },
    play: "Jouer",
    stop: "Arrêter",
    save: "Enregistrer",
    saved: "Enregistré",
    saving: "Enregistrement...",
    addSquare: "Ajouter une case",
    addLine: "Ajouter une ligne",
    removeLine: "Supprimer la ligne",
    clearChord: "Effacer",
    searchChord: "Rechercher un accord...",
    emptySquare: "Vide",
    noGrids: "Aucune grille. Créez votre première !",
    deleteGrid: "Supprimer",
    deleteGridConfirm: "Voulez-vous vraiment supprimer cette grille ?",
    createdAt: "Créée le {{date}}",
    loadError: "Impossible de charger la grille.",
    noResults: "Aucun accord trouvé.",
    dragToReorder: "Glisser pour réordonner",
    repeatCount: "Répétitions",
    mergeGroup: "Fusionner les groupes",
    deleteGroup: "Supprimer le groupe",
    splitHere: "Séparer ici",
    splitGroup: "Séparer le groupe à cette ligne",
    selectedCount: "{{count}} sélectionné(s)",
    groupSelection: "Grouper",
    clearChords: "Effacer les accords",
    deleteSelection: "Supprimer",
    authRequired: "Compte requis",
    authRequiredDescription:
      "Créez un compte pour sauvegarder et gérer vos grilles d'accords.",
    composer: "Compositeur",
    composerPlaceholder: "ex. Miles Davis",
    key: "Tonalité",
    keyPlaceholder: "ex. Dom",
    visibility: "Visibilité",
    private: "Privé",
    public: "Public",
    community: "Communauté",
    searchPublicGrids: "Rechercher par nom, compositeur ou tonalité...",
    publicGrids: "Grilles publiques",
    publicGridsDescription:
      "Parcourez et jouez les grilles partagées par d'autres utilisateurs.",
    noPublicGrids: "Aucune grille publique pour le moment.",
    transpose: "Transposer",
    semitones: "demi-tons",
  },
  tour: {
    helpButton: "Visite",
    back: "Retour",
    next: "Suivant",
    done: "Terminé",
    gridName: {
      title: "Nom de la grille",
      text: "Cliquez sur le nom pour renommer votre progression d'accords.",
    },
    gridOverview: {
      title: "La grille",
      text: "Voici votre grille d'accords. Chaque case représente un accord. Glissez les cases pour les réordonner.",
    },
    gridSquare: {
      title: "Cases d'accords",
      text: "Cliquez sur une case pour ouvrir la recherche et attribuer un accord.",
    },
    chordSearch: {
      title: "Recherche d'accords",
      text: "Tapez pour rechercher des accords. Appuyez sur Entrée pour sélectionner le premier résultat, ou cliquez sur un accord dans la liste.",
    },
    resizeHandle: {
      title: "Nombre de temps",
      text: "Glissez le bord droit d'une case pour changer son nombre de temps entre 2 et 4.",
    },
    addSquare: {
      title: "Ajouter des cases",
      text: "Cliquez sur le bouton + pour ajouter une nouvelle case à votre grille.",
    },
    multiSelect: {
      title: "Sélection multiple",
      text: "Maintenez Ctrl (ou Cmd sur Mac) et cliquez pour sélectionner plusieurs cases. Utilisez Maj+Clic pour sélectionner une plage.",
    },
    selectionToolbar: {
      title: "Actions de sélection",
      text: "Quand des cases sont sélectionnées, utilisez cette barre pour les grouper, effacer leurs accords ou les supprimer.",
    },
    playButton: {
      title: "Lecture",
      text: "Appuyez sur Jouer pour écouter votre progression. Appuyez sur Arrêter pour mettre en pause.",
    },
    tempo: {
      title: "Tempo",
      text: "Réglez la vitesse de lecture en battements par minute (30-300 BPM).",
    },
    loops: {
      title: "Boucles",
      text: "Définissez combien de fois la grille se répète pendant la lecture.",
    },
    instruments: {
      title: "Instruments",
      text: "Activez ou désactivez les instruments : métronome, accords, basse et batterie.",
    },
    styleSelect: {
      title: "Style musical",
      text: "Choisissez un style comme Rock, Jazz ou Bossa Nova pour changer le pattern d'accompagnement.",
    },
    swing: {
      title: "Swing",
      text: "Ajustez le swing de droit (0%) à swing complet (100%).",
    },
    saveButton: {
      title: "Enregistrer",
      text: "Enregistrez votre grille. Le bouton est actif quand vous avez des modifications non sauvegardées.",
    },
  },
  settings: {
    title: "Paramètres",
    language: "Langue",
    languageDescription: "Choisissez la langue de l'interface.",
    notation: "Notation",
    notationDescription:
      "Choisissez l'affichage des notes : lettres (A, B, C) ou solfège (Do, Ré, Mi).",
    theme: "Thème",
    themeDescription: "Choisissez le thème de couleur de l'application.",
    dangerZone: "Zone de danger",
    deleteAccount: "Supprimer le compte",
    deleteAccountDescription:
      "Supprimez définitivement votre compte et toutes les données associées. Cette action est irréversible.",
    deleteAccountConfirmation:
      "Cela supprimera définitivement votre compte, votre progression et toutes vos données. Cette action est irréversible.",
    typeDelete: 'Tapez "DELETE" pour confirmer :',
    deleteButton: "Supprimer mon compte",
    deleting: "Suppression...",
  },
} as const;
