export default {
  common: {
    pianito: "pianito",
    signIn: "登录",
    signUp: "注册",
    signOut: "退出登录",
    settings: "设置",
    retry: "重试",
    previous: "上一个",
    next: "下一个",
    start: "开始",
    loading: "加载中...",
    cancel: "取消",
  },
  home: {
    tagline: "学钢琴，读乐谱，掌握和弦。",
    readMusic: "读谱",
    readMusicDescription: "通过互动练习学习阅读乐谱。",
    chords: "和弦",
    chordsDescription: "通过音阶度数可视化学习和弦。",
    playSongs: "演奏歌曲",
    playSongsDescription: "跟随伴奏音轨一起演奏。",
    accompaniment: "伴奏",
    accompanimentDescription: "创建和弦表并播放。",
  },
  auth: {
    createAccount: "创建账户",
    startJourney: "开始你的钢琴之旅。",
    welcomeBack: "欢迎回到 pianito。",
    name: "姓名",
    namePlaceholder: "你的姓名",
    email: "邮箱",
    emailPlaceholder: "you@example.com",
    password: "密码",
    passwordPlaceholder: "••••••••",
    creatingAccount: "正在创建账户...",
    signingIn: "正在登录...",
    failedCreate: "创建账户失败",
    failedSignIn: "登录失败",
    alreadyHaveAccount: "已有账户？",
    dontHaveAccount: "没有账户？",
  },
  read: {
    title: "读谱",
    description: "从自然音到四个变音记号，逐步进阶。",
    trebleClef: "高音谱号",
    bassClef: "低音谱号",
    levels: "关卡",
    level: "第 {{level}} 关",
    levelProgress: "第 {{current}}/{{total}} 关",
    score: "分数：{{score}}/{{total}}",
    nextLevel: "下一关",
    correct: "正确！",
    wrong: "错误！",
    loadingExercise: "加载练习中...",
    instructions:
      "按任意音符按钮开始。当音符到达橙色区域时识别它。你也可以使用键盘（C、D、E、F、G、A、B）。",
    notesAndTempo: "{{degrees}} 个音符 · {{tempo}} bpm",
  },
  intro: {
    thisIsA: "这是一个 ",
    dontShowAgain: "本关不再显示",
    pageProgress: "{{current}} / {{total}}",
  },
  results: {
    exerciseComplete: "练习完成！",
    scoreDisplay: "{{score}}/{{total}}",
    perfectScore: "满分！",
    greatJob: "做得好！",
    keepPracticing: "继续练习！",
  },
  accomp: {
    title: "伴奏",
    description: "创建和弦表并播放。",
    createNew: "新建网格",
    untitled: "未命名",
    gridName: "网格名称",
    tempo: "速度",
    bpm: "BPM",
    loopCount: "循环次数",
    play: "播放",
    stop: "停止",
    save: "保存",
    saved: "已保存",
    saving: "保存中...",
    addLine: "添加行",
    removeLine: "删除行",
    clearChord: "清除",
    searchChord: "搜索和弦...",
    emptySquare: "空",
    noGrids: "还没有网格。创建你的第一个吧！",
    deleteGrid: "删除",
    deleteGridConfirm: "确定要删除这个网格吗？",
    createdAt: "创建于 {{date}}",
    loadError: "加载网格失败。",
    noResults: "没有匹配的和弦。",
    dragToReorder: "拖动以重新排序",
    repeatCount: "重复次数",
    mergeGroup: "合并组",
    splitHere: "在此分割",
    splitGroup: "在此行分割组",
    selectedCount: "已选择 {{count}} 个",
    groupSelection: "分组",
    authRequired: "需要账户",
    authRequiredDescription: "创建账户以保存和管理你的和弦表。",
  },
  settings: {
    title: "设置",
    language: "语言",
    languageDescription: "选择应用界面的语言。",
    notation: "记谱法",
    notationDescription:
      "选择音符显示方式：字母（A、B、C）或唱名（Do、Ré、Mi）。",
    theme: "主题",
    themeDescription: "选择应用的颜色主题。",
    dangerZone: "危险区域",
    deleteAccount: "删除账户",
    deleteAccountDescription:
      "永久删除您的账户和所有关联数据。此操作无法撤销。",
    deleteAccountConfirmation:
      "这将永久删除您的账户、进度和所有数据。此操作无法撤销。",
    typeDelete: '输入 "DELETE" 以确认：',
    deleteButton: "删除我的账户",
    deleting: "删除中...",
  },
} as const;
