export default {
  common: {
    pianito: "pianito",
    signIn: "登录",
    signUp: "注册",
    signOut: "退出登录",
    settings: "设置",
    retry: "重试",
    previous: "上一个",
    next: "下一个",
    start: "开始",
    loading: "加载中...",
    cancel: "取消",
  },
  home: {
    tagline: "学钢琴，读乐谱，掌握和弦。",
    readMusic: "读谱",
    readMusicDescription: "通过互动练习学习阅读乐谱。",
    chords: "和弦",
    chordsDescription: "通过音阶度数可视化学习和弦。",
    playSongs: "演奏歌曲",
    playSongsDescription: "跟随伴奏音轨一起演奏。",
    accompaniment: "伴奏",
    accompanimentDescription: "创建和弦表并播放。",
  },
  auth: {
    createAccount: "创建账户",
    startJourney: "开始你的钢琴之旅。",
    welcomeBack: "欢迎回到 pianito。",
    name: "姓名",
    namePlaceholder: "你的姓名",
    email: "邮箱",
    emailPlaceholder: "you@example.com",
    password: "密码",
    passwordPlaceholder: "••••••••",
    creatingAccount: "正在创建账户...",
    signingIn: "正在登录...",
    failedCreate: "创建账户失败",
    failedSignIn: "登录失败",
    alreadyHaveAccount: "已有账户？",
    dontHaveAccount: "没有账户？",
  },
  read: {
    title: "读谱",
    description: "从自然音到四个变音记号，逐步进阶。",
    trebleClef: "高音谱号",
    bassClef: "低音谱号",
    levels: "关卡",
    level: "第 {{level}} 关",
    levelProgress: "第 {{current}}/{{total}} 关",
    score: "分数：{{score}}/{{total}}",
    nextLevel: "下一关",
    correct: "正确！",
    wrong: "错误！",
    loadingExercise: "加载练习中...",
    instructions:
      "按任意音符按钮开始。当音符到达橙色区域时识别它。你也可以使用键盘（C、D、E、F、G、A、B）。",
    notesAndTempo: "{{degrees}} 个音符 · {{tempo}} bpm",
  },
  intro: {
    thisIsA: "这是一个 ",
    dontShowAgain: "本关不再显示",
    pageProgress: "{{current}} / {{total}}",
  },
  results: {
    exerciseComplete: "练习完成！",
    scoreDisplay: "{{score}}/{{total}}",
    perfectScore: "满分！",
    greatJob: "做得好！",
    keepPracticing: "继续练习！",
  },
  accomp: {
    title: "伴奏",
    description: "创建和弦表并播放。",
    createNew: "新建网格",
    untitled: "未命名",
    gridName: "网格名称",
    timeSignature: "拍号",
    tempo: "速度",
    bpm: "BPM",
    loopCount: "循环次数",
    currentLoop: "循环 {{current}}/{{total}}",
    metronome: "节拍器",
    chords: "和弦",
    bass: "贝斯",
    drums: "鼓",
    swing: "摇摆",
    style: "风格",
    styleOff: "关闭",
    styles: {
      rock: "摇滚",
      pop: "流行",
      bossaNova: "波萨诺瓦",
      jazz: "爵士",
      funk: "放克",
      reggae: "雷鬼",
    },
    play: "播放",
    stop: "停止",
    save: "保存",
    saved: "已保存",
    saving: "保存中...",
    addSquare: "添加格子",
    addLine: "添加行",
    removeLine: "删除行",
    clearChord: "清除",
    searchChord: "搜索和弦...",
    emptySquare: "空",
    noGrids: "还没有网格。创建你的第一个吧！",
    deleteGrid: "删除",
    deleteGridConfirm: "确定要删除这个网格吗？",
    createdAt: "创建于 {{date}}",
    loadError: "加载网格失败。",
    noResults: "没有匹配的和弦。",
    dragToReorder: "拖动以重新排序",
    repeatCount: "重复次数",
    mergeGroup: "合并组",
    deleteGroup: "删除分组",
    splitHere: "在此分割",
    splitGroup: "在此行分割组",
    selectedCount: "已选择 {{count}} 个",
    groupSelection: "分组",
    clearChords: "清除和弦",
    deleteSelection: "删除",
    authRequired: "需要账户",
    authRequiredDescription: "创建账户以保存和管理你的和弦表。",
    composer: "作曲家",
    composerPlaceholder: "例如 Miles Davis",
    key: "调号",
    keyPlaceholder: "例如 Cm",
    visibility: "可见性",
    private: "私有",
    public: "公开",
    community: "社区",
    searchPublicGrids: "按名称、作曲家或调号搜索...",
    publicGrids: "公开表格",
    publicGridsDescription: "浏览和播放其他用户分享的表格。",
    noPublicGrids: "暂无公开表格。",
  },
  tour: {
    helpButton: "导览",
    back: "上一步",
    next: "下一步",
    done: "完成",
    gridName: {
      title: "网格名称",
      text: "点击名称来重命名你的和弦进行。",
    },
    gridOverview: {
      title: "网格",
      text: "这是你的和弦网格。每个格子代表一个和弦。拖动格子可以重新排序。",
    },
    gridSquare: {
      title: "和弦格子",
      text: "点击任意格子打开和弦搜索并分配一个和弦。",
    },
    chordSearch: {
      title: "和弦搜索",
      text: "输入以搜索和弦。按 Enter 选择第一个匹配项，或点击列表中的任意和弦。",
    },
    resizeHandle: {
      title: "拍数",
      text: "拖动格子右边缘可以在 2 拍和 4 拍之间切换。",
    },
    addSquare: {
      title: "添加格子",
      text: "点击 + 按钮向网格中添加新格子。",
    },
    multiSelect: {
      title: "多选",
      text: "按住 Ctrl（Mac 上为 Cmd）并点击可选择多个格子。使用 Shift+点击选择一个范围。",
    },
    selectionToolbar: {
      title: "选择操作",
      text: "选中格子后，使用此工具栏来分组、清除和弦或删除它们。",
    },
    playButton: {
      title: "播放",
      text: "按下播放来聆听你的和弦进行。按下停止来暂停。",
    },
    tempo: {
      title: "速度",
      text: "设置每分钟拍数来调节播放速度（30-300 BPM）。",
    },
    loops: {
      title: "循环",
      text: "设置播放时网格重复的次数。",
    },
    instruments: {
      title: "乐器",
      text: "切换演奏的乐器：节拍器、和弦、贝斯和鼓。",
    },
    styleSelect: {
      title: "音乐风格",
      text: "选择摇滚、爵士或波萨诺瓦等音乐风格来改变伴奏模式。",
    },
    swing: {
      title: "摇摆",
      text: "调整摇摆感，从直拍（0%）到完全摇摆（100%）。",
    },
    saveButton: {
      title: "保存",
      text: "保存你的网格。有未保存的更改时按钮会激活。",
    },
  },
  settings: {
    title: "设置",
    language: "语言",
    languageDescription: "选择应用界面的语言。",
    notation: "记谱法",
    notationDescription:
      "选择音符显示方式：字母（A、B、C）或唱名（Do、Ré、Mi）。",
    theme: "主题",
    themeDescription: "选择应用的颜色主题。",
    dangerZone: "危险区域",
    deleteAccount: "删除账户",
    deleteAccountDescription:
      "永久删除您的账户和所有关联数据。此操作无法撤销。",
    deleteAccountConfirmation:
      "这将永久删除您的账户、进度和所有数据。此操作无法撤销。",
    typeDelete: '输入 "DELETE" 以确认：',
    deleteButton: "删除我的账户",
    deleting: "删除中...",
  },
} as const;
