import type { DrumPattern, TimeSignatureKey } from "./drum-patterns";

export interface BassNote {
  offset: number;
  velocity: number;
}

export interface BassPattern {
  /** Same subdivision grid as the drum pattern */
  subdivision: "16n" | "8t";
  /**
   * Semitone offsets from the chord root with velocity, or null for rests.
   * offset: 0 = root, 7 = fifth, 12 = octave, -5 = fifth below, etc.
   * velocity: 0-1 intensity.
   */
  notes: (BassNote | null)[];
}

export interface PianoPattern {
  subdivision: "16n" | "8t";
  /** Velocity (0-1) per step, null = rest */
  hits: (number | null)[];
}

export type BassPreset = "fingered" | "walking" | "synth";
export type PianoPreset = "grand" | "rhodes" | "clav" | "organ";

export interface Style {
  drums: Partial<Record<TimeSignatureKey, DrumPattern>>;
  bass: Partial<Record<TimeSignatureKey, BassPattern>>;
  piano: Partial<Record<TimeSignatureKey, PianoPattern>>;
  bassPreset: BassPreset;
  pianoPreset: PianoPreset;
}

/* ── helper to keep patterns compact ────────────────────────────── */
const b = (offset: number, velocity = 0.8): BassNote => ({
  offset,
  velocity,
});

export const STYLES = {
  /* ───────────────────────── ROCK ───────────────────────────────── */
  rock: {
    bassPreset: "fingered",
    pianoPreset: "grand",
    drums: {
      "4/4": {
        subdivision: "16n",
        //        1  .  .  .   2  .  .  .   3  .  .  .   4  .  .  .
        kick: [
          0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        snare: [
          null,
          null,
          null,
          null,
          0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.9,
          null,
          null,
          null,
        ],
        hihat: [
          0.8,
          null,
          0.5,
          null,
          0.8,
          null,
          0.5,
          null,
          0.8,
          null,
          0.5,
          null,
          0.8,
          null,
          0.5,
          null,
        ],
      },
      "3/4": {
        subdivision: "16n",
        //        1  .  .  .   2  .  .  .   3  .  .  .
        kick: [
          0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        snare: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.8,
          null,
          null,
          null,
        ],
        hihat: [
          0.8,
          null,
          0.5,
          null,
          0.8,
          null,
          0.5,
          null,
          0.8,
          null,
          0.5,
          null,
        ],
      },
      "2/4": {
        subdivision: "16n",
        //        1  .  .  .   2  .  .  .
        kick: [0.9, null, null, null, null, null, null, null],
        snare: [null, null, null, null, 0.9, null, null, null],
        hihat: [0.8, null, 0.5, null, 0.8, null, 0.5, null],
      },
      "6/8": {
        subdivision: "8t",
        //        1   .   .    2   .   .    3   .   .    4   .   .
        kick: [
          0.9,
          null,
          null,
          null,
          null,
          null,
          0.8,
          null,
          null,
          null,
          null,
          null,
        ],
        snare: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        hihat: [
          0.8,
          null,
          null,
          0.6,
          null,
          null,
          0.8,
          null,
          null,
          0.6,
          null,
          null,
        ],
      },
      "5/4": {
        subdivision: "16n",
        //        1  .  .  .   2  .  .  .   3  .  .  .   4  .  .  .   5  .  .  .
        kick: [
          0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.8,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        snare: [
          null,
          null,
          null,
          null,
          0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.8,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        hihat: [
          0.8,
          null,
          0.5,
          null,
          0.8,
          null,
          0.5,
          null,
          0.8,
          null,
          0.5,
          null,
          0.8,
          null,
          0.5,
          null,
          0.8,
          null,
          0.5,
          null,
        ],
      },
      "2/2": {
        subdivision: "16n",
        kick: [
          0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        snare: [
          null,
          null,
          null,
          null,
          0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.9,
          null,
          null,
          null,
        ],
        hihat: [
          0.8,
          null,
          0.5,
          null,
          0.8,
          null,
          0.5,
          null,
          0.8,
          null,
          0.5,
          null,
          0.8,
          null,
          0.5,
          null,
        ],
      },
    },
    bass: {
      "4/4": {
        subdivision: "16n",
        //          1  .  .  .   2  .  .  .   3  .  .  .   4  .  .  .
        notes: [
          b(0, 0.9),
          null,
          null,
          null,
          null,
          null,
          null,
          b(0, 0.6),
          b(7, 0.8),
          null,
          null,
          null,
          null,
          null,
          null,
          b(5, 0.7),
        ],
      },
      "3/4": {
        subdivision: "16n",
        notes: [
          b(0, 0.9),
          null,
          null,
          null,
          null,
          null,
          null,
          b(0, 0.6),
          b(7, 0.7),
          null,
          null,
          null,
        ],
      },
      "2/4": {
        subdivision: "16n",
        notes: [b(0, 0.9), null, null, null, null, null, null, b(7, 0.7)],
      },
      "6/8": {
        subdivision: "8t",
        notes: [
          b(0, 0.9),
          null,
          null,
          b(7, 0.6),
          null,
          null,
          b(0, 0.7),
          null,
          null,
          b(5, 0.6),
          null,
          null,
        ],
      },
      "5/4": {
        subdivision: "16n",
        notes: [
          b(0, 0.9),
          null,
          null,
          null,
          null,
          null,
          null,
          b(0, 0.6),
          b(7, 0.8),
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          b(5, 0.7),
          null,
          null,
          null,
        ],
      },
      "2/2": {
        subdivision: "16n",
        notes: [
          b(0, 0.9),
          null,
          null,
          null,
          null,
          null,
          null,
          b(0, 0.6),
          b(7, 0.8),
          null,
          null,
          null,
          null,
          null,
          null,
          b(5, 0.7),
        ],
      },
    },
    piano: {
      "4/4": {
        subdivision: "16n",
        //          1  .  .  .   2  .  .  .   3  .  .  .   4  .  .  .
        hits: [
          0.8,
          null,
          null,
          null,
          0.6,
          null,
          null,
          null,
          0.8,
          null,
          null,
          null,
          0.6,
          null,
          null,
          null,
        ],
      },
      "3/4": {
        subdivision: "16n",
        hits: [
          0.8,
          null,
          null,
          null,
          0.6,
          null,
          null,
          null,
          0.6,
          null,
          null,
          null,
        ],
      },
      "2/4": {
        subdivision: "16n",
        hits: [0.8, null, null, null, 0.6, null, null, null],
      },
    },
  },

  /* ───────────────────────── POP ────────────────────────────────── */
  pop: {
    bassPreset: "fingered",
    pianoPreset: "grand",
    drums: {
      "4/4": {
        subdivision: "16n",
        kick: [
          0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.8,
          null,
          0.7,
          null,
          null,
          null,
          null,
          null,
        ],
        snare: [
          null,
          null,
          null,
          null,
          0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.9,
          null,
          null,
          null,
        ],
        hihat: [
          0.8,
          null,
          0.5,
          null,
          0.7,
          null,
          0.5,
          null,
          0.8,
          null,
          0.5,
          null,
          0.7,
          null,
          0.5,
          null,
        ],
      },
      "3/4": {
        subdivision: "16n",
        kick: [
          0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        snare: [
          null,
          null,
          null,
          null,
          0.9,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        hihat: [
          0.8,
          null,
          0.5,
          null,
          0.7,
          null,
          0.5,
          null,
          0.8,
          null,
          0.5,
          null,
        ],
      },
    },
    bass: {
      "4/4": {
        subdivision: "16n",
        notes: [
          b(0, 0.9),
          null,
          null,
          null,
          null,
          null,
          null,
          b(0, 0.6),
          b(7, 0.8),
          null,
          null,
          null,
          null,
          null,
          null,
          b(5, 0.7),
        ],
      },
      "3/4": {
        subdivision: "16n",
        notes: [
          b(0, 0.9),
          null,
          null,
          null,
          null,
          null,
          null,
          b(0, 0.6),
          b(7, 0.7),
          null,
          null,
          null,
        ],
      },
    },
    piano: {
      "4/4": {
        subdivision: "16n",
        //  Steady eighths, accent on downbeats
        //          1  .  .  .   2  .  .  .   3  .  .  .   4  .  .  .
        hits: [
          0.8,
          null,
          0.5,
          null,
          0.7,
          null,
          0.5,
          null,
          0.8,
          null,
          0.5,
          null,
          0.7,
          null,
          0.5,
          null,
        ],
      },
      "3/4": {
        subdivision: "16n",
        hits: [
          0.8,
          null,
          0.5,
          null,
          0.7,
          null,
          0.5,
          null,
          0.7,
          null,
          0.5,
          null,
        ],
      },
    },
  },

  /* ───────────────────────── BOSSA NOVA ─────────────────────────── */
  bossaNova: {
    bassPreset: "synth",
    pianoPreset: "rhodes",
    drums: {
      "4/4": {
        subdivision: "16n",
        //          1  .  .  .   2  .  .  .   3  .  .  .   4  .  .  .
        kick: [
          0.8,
          null,
          null,
          null,
          null,
          null,
          0.7,
          null,
          null,
          null,
          0.8,
          null,
          null,
          null,
          null,
          null,
        ],
        snare: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        hihat: [
          null,
          null,
          null,
          null,
          0.6,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.6,
          null,
          null,
          null,
        ],
        ride: [
          0.7,
          null,
          null,
          0.5,
          null,
          null,
          0.7,
          null,
          null,
          null,
          0.7,
          null,
          null,
          0.5,
          null,
          null,
        ],
        shaker: [
          0.5,
          null,
          0.3,
          null,
          0.5,
          null,
          0.3,
          null,
          0.5,
          null,
          0.3,
          null,
          0.5,
          null,
          0.3,
          null,
        ],
      },
    },
    bass: {
      "4/4": {
        subdivision: "16n",
        notes: [
          b(0, 0.8),
          null,
          null,
          null,
          null,
          null,
          b(7, 0.6),
          null,
          null,
          null,
          b(0, 0.7),
          null,
          null,
          b(7, 0.6),
          null,
          null,
        ],
      },
    },
    piano: {
      "4/4": {
        subdivision: "16n",
        //  Classic bossa comping: 1, &2, &3, 4
        //          1  .  .  .   2  .  .  .   3  .  .  .   4  .  .  .
        hits: [
          0.7,
          null,
          null,
          null,
          null,
          null,
          0.6,
          null,
          null,
          null,
          0.6,
          null,
          null,
          null,
          0.7,
          null,
        ],
      },
    },
  },

  /* ───────────────────────── JAZZ ───────────────────────────────── */
  jazz: {
    bassPreset: "walking",
    pianoPreset: "rhodes",
    drums: {
      "4/4": {
        subdivision: "8t",
        //        1   &   a    2   &   a    3   &   a    4   &   a
        kick: [
          0.6,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        snare: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        hihat: [
          null,
          null,
          null,
          0.6,
          null,
          null,
          null,
          null,
          null,
          0.6,
          null,
          null,
        ],
        ride: [
          0.8,
          null,
          null,
          0.6,
          null,
          0.5,
          0.8,
          null,
          null,
          0.6,
          null,
          0.5,
        ],
      },
      "3/4": {
        subdivision: "8t",
        //        1   &   a    2   &   a    3   &   a
        kick: [0.6, null, null, null, null, null, null, null, null],
        snare: [null, null, null, null, null, null, null, null, null],
        hihat: [null, null, null, 0.6, null, null, null, null, null],
        ride: [0.8, null, null, 0.6, null, 0.5, 0.8, null, null],
      },
      "5/4": {
        subdivision: "8t",
        //        1   &   a    2   &   a    3   &   a    4   &   a    5   &   a
        kick: [
          0.6,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        snare: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        hihat: [
          null,
          null,
          null,
          0.6,
          null,
          null,
          null,
          null,
          null,
          0.6,
          null,
          null,
          null,
          null,
          null,
        ],
        ride: [
          0.8,
          null,
          null,
          0.6,
          null,
          0.5,
          0.8,
          null,
          null,
          0.6,
          null,
          0.5,
          0.8,
          null,
          null,
        ],
      },
    },
    bass: {
      "4/4": {
        subdivision: "8t",
        //  Walking bass: root, 3rd, 5th, approach tone
        notes: [
          b(1, 0.9),
          null,
          null,
          b(3, 0.6),
          null,
          null,
          b(7, 0.7),
          null,
          null,
          b(5, 0.6),
          null,
          null,
        ],
      },
      "3/4": {
        subdivision: "8t",
        notes: [
          b(1, 0.9),
          null,
          null,
          b(3, 0.6),
          null,
          null,
          b(7, 0.7),
          null,
          null,
        ],
      },
      "5/4": {
        subdivision: "8t",
        notes: [
          b(1, 0.9),
          null,
          null,
          b(3, 0.6),
          null,
          null,
          b(7, 0.7),
          null,
          null,
          b(5, 0.6),
          null,
          null,
          b(0, 0.7),
          null,
          null,
        ],
      },
    },
    piano: {
      "4/4": {
        subdivision: "8t",
        //  Comping on 2 and 4 with anticipation on &4
        //          1   &   a    2   &   a    3   &   a    4   &   a
        hits: [
          null,
          null,
          null,
          0.7,
          null,
          null,
          null,
          null,
          null,
          0.7,
          null,
          0.4,
        ],
      },
      "3/4": {
        subdivision: "8t",
        hits: [null, null, null, 0.7, null, null, null, null, null],
      },
    },
  },

  /* ───────────────────────── FUNK ───────────────────────────────── */
  funk: {
    bassPreset: "synth",
    pianoPreset: "clav",
    drums: {
      "4/4": {
        subdivision: "16n",
        //        1  .  .  .   2  .  .  .   3  .  .  .   4  .  .  .
        kick: [
          0.9,
          null,
          null,
          0.7,
          null,
          null,
          null,
          null,
          null,
          null,
          0.8,
          null,
          null,
          null,
          null,
          null,
        ],
        snare: [
          null,
          null,
          0.2,
          null,
          0.9,
          null,
          null,
          0.4,
          null,
          0.3,
          null,
          null,
          0.9,
          null,
          0.4,
          null,
        ],
        hihat: [
          0.8,
          null,
          0.5,
          null,
          0.7,
          null,
          0.5,
          null,
          0.8,
          null,
          0.5,
          null,
          0.7,
          null,
          0.5,
          null,
        ],
      },
    },
    bass: {
      "4/4": {
        subdivision: "16n",
        notes: [
          b(0, 0.9),
          null,
          null,
          b(0, 0.7),
          null,
          null,
          b(7, 0.8),
          null,
          null,
          null,
          b(0, 0.7),
          null,
          null,
          b(0, 0.6),
          b(5, 0.8),
          null,
        ],
      },
    },
    piano: {
      "4/4": {
        subdivision: "16n",
        //  Choppy 16th stabs — syncopated funk comping
        //          1  .  .  .   2  .  .  .   3  .  .  .   4  .  .  .
        hits: [
          0.7,
          null,
          0.4,
          null,
          null,
          null,
          0.6,
          null,
          null,
          0.4,
          null,
          null,
          0.7,
          null,
          null,
          0.5,
        ],
      },
    },
  },

  /* ───────────────────────── REGGAE ─────────────────────────────── */
  reggae: {
    bassPreset: "fingered",
    pianoPreset: "organ",
    drums: {
      "4/4": {
        subdivision: "16n",
        //        1  .  .  .   2  .  .  .   3  .  .  .   4  .  .  .
        kick: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.8,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        snare: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0.7,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
        ],
        hihat: [
          null,
          null,
          0.6,
          null,
          null,
          null,
          0.6,
          null,
          null,
          null,
          0.6,
          null,
          null,
          null,
          0.6,
          null,
        ],
      },
    },
    bass: {
      "4/4": {
        subdivision: "16n",
        notes: [
          b(0, 0.9),
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          b(0, 0.7),
          null,
          null,
          b(7, 0.6),
          null,
          null,
          b(5, 0.7),
          null,
        ],
      },
    },
    piano: {
      "4/4": {
        subdivision: "16n",
        //  Offbeat skank: &1, &2, &3, &4
        //          1  .  .  .   2  .  .  .   3  .  .  .   4  .  .  .
        hits: [
          null,
          null,
          0.7,
          null,
          null,
          null,
          0.7,
          null,
          null,
          null,
          0.7,
          null,
          null,
          null,
          0.7,
          null,
        ],
      },
    },
  },
} as const satisfies Record<string, Style>;

export type StyleId = keyof typeof STYLES;

export const STYLE_IDS = Object.keys(STYLES) as StyleId[];

export function isStyleId(value: string): value is StyleId {
  return (STYLE_IDS as readonly string[]).includes(value);
}
