/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReadRouteImport } from './routes/read'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccompRouteImport } from './routes/accomp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadIndexRouteImport } from './routes/read.index'
import { Route as AccompIndexRouteImport } from './routes/accomp.index'
import { Route as ReadLevelRouteImport } from './routes/read.$level'
import { Route as AccompGridIdRouteImport } from './routes/accomp.$gridId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccompRoute = AccompRouteImport.update({
  id: '/accomp',
  path: '/accomp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadIndexRoute = ReadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReadRoute,
} as any)
const AccompIndexRoute = AccompIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccompRoute,
} as any)
const ReadLevelRoute = ReadLevelRouteImport.update({
  id: '/$level',
  path: '/$level',
  getParentRoute: () => ReadRoute,
} as any)
const AccompGridIdRoute = AccompGridIdRouteImport.update({
  id: '/$gridId',
  path: '/$gridId',
  getParentRoute: () => AccompRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accomp': typeof AccompRouteWithChildren
  '/login': typeof LoginRoute
  '/read': typeof ReadRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/accomp/$gridId': typeof AccompGridIdRoute
  '/read/$level': typeof ReadLevelRoute
  '/accomp/': typeof AccompIndexRoute
  '/read/': typeof ReadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/accomp/$gridId': typeof AccompGridIdRoute
  '/read/$level': typeof ReadLevelRoute
  '/accomp': typeof AccompIndexRoute
  '/read': typeof ReadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accomp': typeof AccompRouteWithChildren
  '/login': typeof LoginRoute
  '/read': typeof ReadRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/accomp/$gridId': typeof AccompGridIdRoute
  '/read/$level': typeof ReadLevelRoute
  '/accomp/': typeof AccompIndexRoute
  '/read/': typeof ReadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accomp'
    | '/login'
    | '/read'
    | '/settings'
    | '/signup'
    | '/accomp/$gridId'
    | '/read/$level'
    | '/accomp/'
    | '/read/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/signup'
    | '/accomp/$gridId'
    | '/read/$level'
    | '/accomp'
    | '/read'
  id:
    | '__root__'
    | '/'
    | '/accomp'
    | '/login'
    | '/read'
    | '/settings'
    | '/signup'
    | '/accomp/$gridId'
    | '/read/$level'
    | '/accomp/'
    | '/read/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccompRoute: typeof AccompRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReadRoute: typeof ReadRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accomp': {
      id: '/accomp'
      path: '/accomp'
      fullPath: '/accomp'
      preLoaderRoute: typeof AccompRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/': {
      id: '/read/'
      path: '/'
      fullPath: '/read/'
      preLoaderRoute: typeof ReadIndexRouteImport
      parentRoute: typeof ReadRoute
    }
    '/accomp/': {
      id: '/accomp/'
      path: '/'
      fullPath: '/accomp/'
      preLoaderRoute: typeof AccompIndexRouteImport
      parentRoute: typeof AccompRoute
    }
    '/read/$level': {
      id: '/read/$level'
      path: '/$level'
      fullPath: '/read/$level'
      preLoaderRoute: typeof ReadLevelRouteImport
      parentRoute: typeof ReadRoute
    }
    '/accomp/$gridId': {
      id: '/accomp/$gridId'
      path: '/$gridId'
      fullPath: '/accomp/$gridId'
      preLoaderRoute: typeof AccompGridIdRouteImport
      parentRoute: typeof AccompRoute
    }
  }
}

interface AccompRouteChildren {
  AccompGridIdRoute: typeof AccompGridIdRoute
  AccompIndexRoute: typeof AccompIndexRoute
}

const AccompRouteChildren: AccompRouteChildren = {
  AccompGridIdRoute: AccompGridIdRoute,
  AccompIndexRoute: AccompIndexRoute,
}

const AccompRouteWithChildren =
  AccompRoute._addFileChildren(AccompRouteChildren)

interface ReadRouteChildren {
  ReadLevelRoute: typeof ReadLevelRoute
  ReadIndexRoute: typeof ReadIndexRoute
}

const ReadRouteChildren: ReadRouteChildren = {
  ReadLevelRoute: ReadLevelRoute,
  ReadIndexRoute: ReadIndexRoute,
}

const ReadRouteWithChildren = ReadRoute._addFileChildren(ReadRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccompRoute: AccompRouteWithChildren,
  LoginRoute: LoginRoute,
  ReadRoute: ReadRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
